### ISSUE TITLE
Add ability to convert exception objects to JSON

### ISSUE THREAD

**Issue by otisg** [ReactiveMarkets/NLog.Targets.ElasticSearch#14]
Opening this issue on the behalf of a Logsene user (see http://sematext.com/logsene).
He's using NLog ES target and hoping one of the fields he is sending -- the one holding the exception stack traces -- would be turned into JSON.  My understanding based on what this person said is that some other NLog targets automatically convert some fields/objects to JSON.  I have never worked with NLog, so I'm not sure about the details, but if that is the case, if that is something that NLog targts do, maybe the ES one should do that, too?

Here is his NLog ES target config:

```xml
  <target name="elastic" xsi:type="BufferingWrapper" flushTimeout="5000">
      <target xsi:type="ElasticSearch" Index="xxxx-${date:format=yyyy.MM.dd}" Uri="https://logsene-receiver.sematext.com" includeAllProperties="true">
        <field name="user" layout="${windows-identity:userName=True:domain=False}"/>
        <field name="host" layout="${machinename}"/>
        <field name="number" layout="${counter:increment=1:sequence=String:value=1}"/>
      </target>
    </target>
```

**Comment by markmcdowell** [comment]
I assuming what he means is using the [JsonLayout](https://github.com/NLog/NLog/wiki/JsonLayout) to convert the field. Should work fine with this target, possibly something like (I haven't checked it):
```xml
<target name="elastic" xsi:type="BufferingWrapper" flushTimeout="5000">
  <target xsi:type="ElasticSearch" Index="xxxx-${date:format=yyyy.MM.dd}" Uri="https://logsene-receiver.sematext.com" includeAllProperties="true">
    <layout xsi:type="JsonLayout">
      <attribute name="time" layout="${longdate}" />
      <attribute name="level" layout="${level:upperCase=true}"/>
      <attribute name="message" layout="${message}" />
   </layout>
  </target>
</target>
```

**Comment by otisg** [comment]
I suspect he didn't use that because he didn't mention it and his config doesn't include it.  I pointed him to this issue, so maybe he'll comment on this.

**Comment by markmcdowell** [comment]
Ok the only other thing I can think is that the fields is already a JSON string. In that case as long as the elasticsearch index is setup correctly it will parse it.

**Comment by sturk** [comment]
hi Mark,
I was using NLog.Targets.RabbitMQ. When log error Nlog.error (message, Exception). Ex was serialized as json and ship to ES. this is very helpful cases like to group exception types, or group exception message from web services. Also I try  suggested option above, it does not display as key value pair. 

this what I get:

"message": "{ \"time\": \"2016-03-24 16:16:39.8446\", \"level\": \"INFO\", \"message\": \"Hello, Logsene!\" }"

Sample Exception object json from kibana:
"exception": {
      "StackTraceString": "   at LogManagementIntegrationDemo.Program.nlogTest()",
      "Message": "Error in the application.",
      "HResult": -2146232832,
      "RemoteStackTraceString": null,
      "ClassName": "System.ApplicationException",
      "InnerException": null,
      "Data": null,
      "WatsonBuckets": null,
      "RemoteStackIndex": 0,
      "ExceptionMethod": "8\nnlogTest\nLogManagementIntegrationDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\nLogManagementIntegrationDemo.Program\nVoid nlogTest()",
      "HelpURL": null,
      "Source": "LogManagementIntegrationDemo"

**Comment by markmcdowell** [comment]
Ok, yeah I can see it has a useJson flag and converts the exception object to json. I'm planning on doing a tidy later today so will add this as an option.

**Comment by markmcdowell** [comment]
Supported in 1.1.0 by default. Now on Nuget
