### ISSUE TITLE
net45 dll contains net452 dll in nuget package

### ISSUE THREAD

**Issue by luuksommers** [ReactiveMarkets/NLog.Targets.ElasticSearch#15]
When I install the latest nuget package (2.0.1) I get an warning that my .net 4.5 project references a newer dependency (which is the NLog.Targets.ElasticSearch.dll). I've verified the path and it points to the net45 in the nuget Package.

`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "NLog.Targets.ElasticSearch" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".`

The project file contains

    <Reference Include="NLog.Targets.ElasticSearch">
        <HintPath>..\..\Packages\NLog.Targets.ElasticSearch.2.0.1.0\lib\net45\NLog.Targets.ElasticSearch.dll</HintPath>
        <Private>True</Private>
    </Reference>

**Comment by markmcdowell** [comment]
Thanks mistake from last upgrade. Corrected in 2.0.3, now live on Nuget
