### ISSUE TITLE
Enhancement: Make Uri a Layout parameter

### ISSUE THREAD

**Issue by Matthew-Davey** [ReactiveMarkets/NLog.Targets.ElasticSearch#20]
It would be great if uri was a Layout parameter such as Index, DocumentType etc.

This would allow us to construct the connection string from environment variables eg.
```
<target type=ElasticSearch" uri="http://${environment:variable=ES_HOST}:9200" ... />
```
Bonus points if we can set connectionStringName and still have this functionality :smile:

**Comment by markmcdowell** [comment]
The problem with making it a layout is that you need a logEvent object to evaluate it and you only get those when logging out.

It's not obvious and not great code but you can actually set the connectionStringName to the name of an environment variable and it will use it.

**Comment by Matthew-Davey** [comment]
Worked around this by using Logstash instead of logging directly to elasticsearch.
