### ISSUE TITLE
update to dotnetcore 

### ISSUE THREAD

**Issue by damienbod** [ReactiveMarkets/NLog.Targets.ElasticSearch#23]
Thanks for the library.

I've created a dotnetcore project based on your @peske pull request and your @markmcdowell library.

@peske @markmcdowell 
https://github.com/damienbod/AspNetCoreNlog/tree/master/src/NLog.Targets.ElasticSearch

Would you like to use this, or update your pull request, or should I create my own pull request for this?

It would be really nice to update this project.

Greetings Damien

**Comment by pholly** [comment]
Yes the dust is finally settling on dotnetcore. Visual Studio 2017 RTM coming out next week. I'd like to use this project in my asp.net core solutions. Thank you for creating it.

**Comment by markmcdowell** [comment]
We need the build server to support this, so hopefully it will be updated this week once vs 2017 RTM is out and we can support dot net core.

**Comment by damienbod** [comment]
appveyor has a build server which supports this.

**Comment by markmcdowell** [comment]
Ok great i'll test this out tomorrow with VS2017 and get it packaging for multiple targets.

**Comment by markmcdowell** [comment]
I have this working on the net-standard branch but appveyor can't build it yet. Support should be added some point this week, NLog is also still in beta for .net standard so I may wait until that is finished.

**Comment by markmcdowell** [comment]
Now building on appveyor, published as 4.0.0-beta19 while NLog is still in beta.
