### ISSUE TITLE
Which all versions of ElasticSearch are compatible with NLog.Targets.ElasticSearch(2.1.8)

### ISSUE THREAD

**Issue by ImdotnetJunkie** [ReactiveMarkets/NLog.Targets.ElasticSearch#34]
We are currently on ElasticSearch (1.7.5) and using NLog.Targets.ElasticSearch(1.1.1.0). 
We are going to upgrade our ElasticSearch cluster to 5.x now so does this latest version of NLog.Targets.ElasticSearch(2.1.8) supports this version of ES or not ?

**Comment by markmcdowell** [comment]
yes it does support it for a single url only, multiple urls sniffing doesn't work. We need to upgrade the elasticsearch client to support new features like ingest nodes.

**Comment by markmcdowell** [comment]
Multiple urls now supported in the latest package.

**Comment by ImdotnetJunkie** [comment]
Thanks for the update @markmcdowell
