### ISSUE TITLE
using 2 URIs

### ISSUE THREAD

**Issue by Trysomthing** [ReactiveMarkets/NLog.Targets.ElasticSearch#35]
I’m using 2 UIRs – local & Remote. I have 10 messages/events. I expect all 10 will appear on both elastic servers. What actually happens is the 10 log messages split between the 2 URIs (one has 4 and the other 6)

**Comment by markmcdowell** [comment]
Elasticsearch will load balance across all url's rather than sending to both. You would have to add mulitple nlog targets to send to 2 different instances.
