### ISSUE TITLE
How do I define custom Fields/properties

### ISSUE THREAD

**Issue by howiecamp** [ReactiveMarkets/NLog.Targets.ElasticSearch#41]
Hi - please see my question at https://stackoverflow.com/questions/45087065/how-to-define-custom-field-mappings-with-nlog-elasticsearch-target.

**Comment by markmcdowell** [comment]
Hey, so the fields are of type layout so you can use any of the nlog layout renderers on the custom fields.

It sounds like your asking how to parse the message you set in the log.Info() into json. Is that correct?

**Comment by howiecamp** [comment]
Thanks for getting back to me so quickly.

I think I'm fundamentally confused about how to accomplish what I want to accomplish.  I'm not even sure if the use of `Fields` (the `Fields` object in the nuget package) is the right way to go.

With respect to:

"It sounds like your asking how to parse the message you set in the log.Info() into json. Is that correct?"

I'm not sure.  Obviously any text I include in `log.Info("...");` constitutes the `Message`.  But in Elasticsearch I don't want my custom properties (or fields, I am mixing terminology I know) to be part of the `Message` property; I want them to be standalone fields as shown in the first screenshot.

**Comment by markmcdowell** [comment]
Ok think I understand. 

You need to use the NLog fluent api and set properties. So your code would look like:
```
_logger.Info()
       .Message("your log message.")
       .Property("property1", "value1")
       .Write();
```

And on the elasticsearch target set `IncludeAllProperties=True`

(Caveat I haven't actually tried this in code).

**Comment by aheubusch** [comment]
Changing the number of fields per log message is not feasible I think.
Maybe you can set `includeAllProperties` to true on the target and use message properties. Each property is sent to elasticsearch.

```csharp
var logger = LogManager.GetCurrentClassLogger();
var eventInfo = new LogEventInfo(LogLevel.Info, logger.Name, "Message");
eventInfo.Properties["CustomValue"] = "My custom string";
eventInfo.Properties["CustomDateTimeValue"] = new DateTime(2020, 10, 30, 11, 26, 50);
// You can also add them like this:
eventInfo.Properties.Add("CustomNumber", 42);
// Send to Log
logger.Log(eventInfo);
```
There is also a fluent version. https://github.com/NLog/NLog/wiki/Fluent-API

**Comment by aheubusch** [comment]
... dang, 34 seconds to late :D

**Comment by howiecamp** [comment]
Gents - Perfect!  Both alternatives work (because they're the same thing I guess :)  )!  The only difference is that when done @markmcdowell's way, the elasticsearch index shows a "*propertyname*.keyword" field in addition to the "*propertyname*" field.  (That sounds like an Elasticsearch thing; I'll read up on it.)

@aheubusch What do you mean about changing the number of fields per log message?  In the details of an individual Elasticsearch document I see *only* the fields for the properties I've set for that particular message, whereas the index definition has a superset of all fields that were ever sent into that index.
