### ISSUE TITLE
Potential performance issue

### ISSUE THREAD

**Issue by pardahlman** [ReactiveMarkets/NLog.Targets.ElasticSearch#45]
Hi, thanks for an easy-to-use target to sync entries to Elasticsearch 👍 

I did some benchmarking by running a set of integration tests with and without the Elastic target. To my surprise, the using this target had an pretty significant impact on my performance. In fact, it more than doubled the duration of the test suite (from 6m50s to 13m56s).

I figured that I must be doing something wrong when configuring the target, but reading closely here it feels like I'm following the recommendations. I configure the target in code

```csharp
var elasticTarget = new ElasticSearchTarget
{
  Uri = settings.Url,
  Password = settings.Password,
  Username = settings.UserName,
  RequireAuth = settings.RequireAuthentication,
  Name = targetName_,
  Index = new SimpleLayout("dev-${date:format=yyyy.MM.dd}"),
  IncludeAllProperties = true,
  OptimizeBufferReuse = true,
  Fields = new List<Field>
  {
    new Field{ Name = "message", Layout = new SimpleLayout("${message")},
    new Field{ Name = "thread", Layout = new SimpleLayout("${threadid}")},
    new Field{ Name = "logger", Layout = new SimpleLayout("${logger}")},
    new Field{ Name = "host", Layout = new SimpleLayout("${environment:variable=COMPUTERNAME}")},
    new Field{ Name = "buildNumber", Layout = new SimpleLayout("${environment:variable=BUILD_BUILDNUMBER}")}
  }
};

var bufferTarget = new BufferingTargetWrapper(elasticTarget, 150, (int)TimeSpan.FromSeconds(5).TotalMilliseconds)
{
  OptimizeBufferReuse = true
};
cfg.AddTarget(targetName_, bufferTarget);
```
Are there any more suggestions on what I might be able to do to increase performance further?

**Comment by snakefoot** [comment]
Don't use the BufferingTargetWrapper, but instead use the AsyncTargetWrapper with the following properties configured `timeToSleepBetweenBatches=0` and `overflowAction=Block`.

The BufferingTargetWrapper is mostly used in situations where you want to slow things down.

**Comment by markmcdowell** [comment]
close, just nlog settings. The performance is better the more logs are batched due to using the bulk elasticsearch api.
