### ISSUE TITLE
Logs not written to ElasticSearch

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [ReactiveMarkets/NLog.Targets.ElasticSearch#53]
I am trying to use the newest beta from nuget, I am using the beta, because we want our log-library to be in .net Core. However nothing is written to ElasticSearch.
I think the problem is that ElasticSearchTarget does not overrice the method Write(LogEventInfo logEvent) from the NLog.Targets.Target class. That causes NLog to just call its own empty class:

        protected virtual void Write(LogEventInfo logEvent)
        {
            // Override to perform the actual write-operation
        }

An implementation in the ElasticSearchTarget like this will write the events:

        protected override void Write(LogEventInfo logEvent)
        {
            Write(new List<AsyncLogEventInfo> {new AsyncLogEventInfo(logEvent, exception => {})});
        }

At least that is my understanding.

**Comment by markmcdowell** [comment]
I took a brief look at the code and it looks like it should still work. I'll have to test again once I get my visual studio working again.

Originally we didn't override that method because you only get a single log event when ideally we should send a batch.

**Comment by snakefoot** [comment]
@markmcdowell Created #55 to fix this.

**Comment by carkov1990** [comment]
This mistake was repeated at me. I could not send logs through FallbackGroup + BufferingWrapper
