### ISSUE TITLE
.Net 4.5 and support for Newtonsoft.JSON 10.0.1

### ISSUE THREAD

**Issue by sboele** [ReactiveMarkets/NLog.Targets.ElasticSearch#57]
We are using Newtonsoft.JSON 10.0.1 in our project and we're running into issues when using this NLog target since it's referencing Newtonsoft.JSON 9.0.1. Is there a specific reason it's using 9.0.1 for .NET 4.5?

Upgrading the project to use Newtonsoft.JSON 10.0.1 seems to work just fine?

**Comment by dragouf** [comment]
if you have a problem with Newtonsoft version add a binding redirect to your .config file :

```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

don't need to change the library for that
