### ISSUE TITLE
One or more errors occurred. (Failed to ping the specified node.)

### ISSUE THREAD

**Issue by disiron** [ReactiveMarkets/NLog.Targets.ElasticSearch#58]
Greetings!

I'm trying to set up logginw to remove ES set up with the following config:

`<target name="elasticLog" xsi:type="BufferingWrapper" flushTimeout="2000">
      <target xsi:type="ElasticSearch"
              name="elastic">
        <field name="shortMessage" layout="${event-properties:item=shortMessage}"/>
        <field name="app" layout="${event-properties:item=app}"/>
        <field name="uri" layout="http://192.168.129.7:9200" />
        
      </target>
    </target>`

However, a connection to ES is failed with the following error:

**_One or more errors occurred. (Failed to ping the specified node.)_**

The server is pingable and reachable from the machine i use nlog on. Is there any know issue regarding this please? I found something similar with NEST:

[](https://discuss.elastic.co/t/elasticsearch-net-nest-connection-string-when-active-directory-turn-on-elasticsearch-authentication/71753/13)

Thanks in advance

**Comment by markmcdowell** [comment]
Your settings would try to ping http://localhost:9200 is that what you want?

I would assume you meant:

```
<target name="elasticLog" xsi:type="BufferingWrapper" flushTimeout="2000"> 
  <target xsi:type="ElasticSearch" 
          name="elastic"
          uri="http://192.168.129.7:9200"> 
    <field name="shortMessage" layout="${event-properties:item=shortMessage}"/>
    <field name="app" layout="${event-properties:item=app}"/> 
  </target>
</target>
```

**Comment by disiron** [comment]
Obviously, wrong settings.. Thanks, closing issue.
