### ISSUE TITLE
Update Elasticsearch.Net to 6.x

### ISSUE THREAD

**Issue by agentschmitt** [ReactiveMarkets/NLog.Targets.ElasticSearch#59]
Could you update Elasticsearch.Net from 5.2.0 to 6.0.x?
It is not possible to use Elasticsearch.Net 6x in our project together with Nlog.Targets.ElasticSearch.
The reason is that there are breaking changes from 5x to 6.x which doesn't allow us to use AssemblyBinding for this case.

**Comment by nianios** [comment]
I second that. Updating to 6.0.x is a necessity.

**Comment by markmcdowell** [comment]
I’ve been waiting for the nlog 4.5 release, which was yesterday. 
So I’ll update tonight.
		
		

		Thanks, Mark
	




On Tue, Mar 27, 2018 at 7:48 AM +0100, "nianios" <notifications@github.com> wrote:












I second that. Updating to 6.0.x is a necessity.

**Comment by nianios** [comment]
Any news on that matter?

**Comment by markmcdowell** [comment]
Done, version 5.0.0 supports elasticsearch 6.
